#!/bin/env bash

mkdir -p PDFs

for f in *.jpg
do
	FILENAME=$(echo "${f%%.*}")
	convert "$f" "$FILENAME.pdf"
	mv "${FILENAME}.pdf" "PDFs"
done

for f in *.jpeg
do
	FILENAME=$(echo "${f%%.*}")
	convert "$f" "$FILENAME.pdf"
	mv "${FILENAME}.pdf" "PDFs"
	rm "$FILENAME.pdf"
done

cd PDFs
