#! /bin/bash

echo
echo "Let's rip this CD! But first, tell me some information:"
echo

read -r -p "Album title: " ALBUM
read -r -p "Artist: " ARTIST
read -r -p "Year: " YEAR
read -r -p "Genre: " GENRE

TARGET_FOLDER="$HOME/SSD/Music/$ARTIST/$YEAR - $ALBUM"

mkdir -p "$TARGET_FOLDER"

cd "$TARGET_FOLDER" || { echo "Something's wrong, aborting..."; exit 1; }

echo
echo "Extracting uncompressed audio tracks..."
echo

cdparanoia -B

echo "Compressing audio tracks with the FLAC codec..."
echo

for f in *.wav
do
	TRACK=$(echo "$f" | cut -c6-7)
	read -r -p "Track $TRACK title: " SONGTITLE
	flac --best -T TITLE="$SONGTITLE" -T ARTIST="$ARTIST" -T ALBUM="$ALBUM" -T DATE="$YEAR" -T TRACKNUMBER="$TRACK" -T GENRE="$GENRE" "$f" -o "$TRACK - $SONGTITLE.flac"
	echo
done

rm -- *.wav

eject /dev/sr0

echo
echo "Done! May the Force be with you!"
echo 
